/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package collections;

public class App {
    public static void main(String[] args) {
    	CollectionsQueueListener.listen();
    }
}
